apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}
  labels:
{{ include "redis.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
---
apiVersion: v1
kind: Endpoints
metadata:
 name: {{.Chart.Name}}
 labels:
{{ include "redis.labels" . | indent 4 }}
subsets:
 - addresses:
     - ip: {{ .Values.service.targetIp }}
   ports:
     - port: {{ .Values.service.targetPort }}