{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "coins.serviceAccountName" . }}
  labels:
{{ include "coins.labels" . | indent 4 }}
{{- end -}}
