projectName: dockercoins
replicaCount: 1
serverName: webui
probeEnabled: true

image:
  repository: dockercoins/webui
  tag: v0.1
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name:

podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 80
  targetPort: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: dev-webui.192.168.33.111.nip.io
      paths: 
        - /
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
