projectName: dockercoins
replicaCount: 1
serverName: redis
probeEnabled: false

image:
  repository: redis
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name:

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 6379
  targetPort: 6379

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: 
      paths: 
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
