apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{.Chart.Name}}
  labels:
{{ include "rng.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "rng.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "rng.labels" . | indent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "rng.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{.Chart.Name}}
          env:
          - name: PROJECT_NAME
            value: {{.Values.projectName}}
          - name: ENVIRONMENT
            value: {{.Release.Namespace}}
          - name: SERVICE_NAME
            value: {{.Chart.Name}}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
