projectName: dockercoins
replicaCount: 1
serverName: webui

image:
  repository: dockercoins/webui
  tag: v0.1
  pullPolicy: IfNotPresent
serviceAccount:
  create: true
service:
  type: NodePort
  port: 80
  targetPort: 80
ingress:
  enabled: true
  hosts:
    - host: webui.192.168.33.111.nip.io
      paths: 
        - /
