projectName: dockercoins
replicaCount: 1

image:
  repository: dockercoins/hasher
  tag: v0.1
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
service:
  type: ClusterIP
  port: 80 

ingress:
  enabled: false
